-- Script de Criação e Configuração das Tabelas no Supabase
-- Cole este script no SQL Editor do Supabase e clique em 'Run'

-- 1. Criação da tabela de Produtos
CREATE TABLE IF NOT EXISTS public.produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PLU" TEXT NOT NULL,
    nome TEXT NOT NULL,
    preco NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    estoque NUMERIC(10, 3) NOT NULL DEFAULT 0,
    pesavel BOOLEAN NOT NULL DEFAULT false,
    controlar_estoque BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Adiciona a coluna na tabela existente caso ela já tenha sido criada (para atualizar o banco anterior)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name='produtos' AND column_name='pesavel'
  ) THEN
    ALTER TABLE public.produtos ADD COLUMN pesavel BOOLEAN NOT NULL DEFAULT false;
    ALTER TABLE public.produtos ALTER COLUMN estoque TYPE NUMERIC(10,3);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name='produtos' AND column_name='controlar_estoque'
  ) THEN
    ALTER TABLE public.produtos ADD COLUMN controlar_estoque BOOLEAN NOT NULL DEFAULT true;
  END IF;
END $$;

-- Garante que não haverá produtos com o mesmo Código de Barras duplicado
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'produtos_plu_unique'
  ) THEN
    ALTER TABLE public.produtos ADD CONSTRAINT produtos_plu_unique UNIQUE ("PLU");
  END IF;
END $$;


-- 2. Criação da tabela de Vendas
CREATE TABLE IF NOT EXISTS public.vendas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    total NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    "totalItens" INTEGER NOT NULL DEFAULT 0,
    cliente TEXT,
    forma_pagamento TEXT NOT NULL,
    itens JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'CONCLUIDA' CHECK (status IN ('CONCLUIDA', 'ENCOMENDA')),
    data_conclusao TIMESTAMP WITH TIME ZONE,
    valor_pago NUMERIC(10, 2),
    troco NUMERIC(10, 2),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Script de Migração para tabelas existentes
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='vendas' AND column_name='status') THEN
    ALTER TABLE public.vendas ADD COLUMN status TEXT NOT NULL DEFAULT 'CONCLUIDA' CHECK (status IN ('CONCLUIDA', 'ENCOMENDA'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='vendas' AND column_name='data_conclusao') THEN
    ALTER TABLE public.vendas ADD COLUMN data_conclusao TIMESTAMP WITH TIME ZONE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='vendas' AND column_name='valor_pago') THEN
    ALTER TABLE public.vendas ADD COLUMN valor_pago NUMERIC(10, 2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='vendas' AND column_name='troco') THEN
    ALTER TABLE public.vendas ADD COLUMN troco NUMERIC(10, 2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='vendas' AND column_name='user_id') THEN
    ALTER TABLE public.vendas ADD COLUMN user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;
END $$;


-- 3. Criação da tabela de Movimentações (com Foreign Key)
CREATE TABLE IF NOT EXISTS public.movimentacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_movimentacao TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    produto_id BIGINT NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('ENTRADA', 'SAÍDA')),
    quantidade INTEGER NOT NULL CHECK (quantidade > 0),
    motivo TEXT,
    
    -- Foreign Key vinculando a movimentação ao produto
    -- ON DELETE CASCADE significa que se o produto for deletado, a movimentação some junto
    CONSTRAINT fk_produto
      FOREIGN KEY(produto_id) 
      REFERENCES public.produtos(id)
      ON DELETE CASCADE
);


-- ========================================================
-- Políticas de Segurança (RLS - Row Level Security)
-- ========================================================

-- Ativar RLS nas tabelas para que os dados sejam protegidos
ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movimentacoes ENABLE ROW LEVEL SECURITY;

-- Exemplo: Criar políticas permitindo acesso apenas a usuários autenticados
-- Obs: Se a sua aplicação compartilha os dados num geral e quem tem login tem acesso irrestrito.

-- PRODUTOS
DROP POLICY IF EXISTS "Permitir leitura para auth" ON public.produtos;
CREATE POLICY "Permitir leitura para auth" ON public.produtos FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Permitir inserção/edição para auth" ON public.produtos;
CREATE POLICY "Permitir inserção/edição para auth" ON public.produtos FOR ALL USING (auth.role() = 'authenticated');

-- VENDAS
DROP POLICY IF EXISTS "Permitir leitura para auth" ON public.vendas;
CREATE POLICY "Permitir leitura para auth" ON public.vendas FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Permitir inserção para auth" ON public.vendas;
CREATE POLICY "Permitir inserção para auth" ON public.vendas FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Permitir atualização para auth" ON public.vendas;
CREATE POLICY "Permitir atualização para auth" ON public.vendas FOR UPDATE USING (auth.role() = 'authenticated');

-- MOVIMENTACOES
DROP POLICY IF EXISTS "Permitir leitura para auth" ON public.movimentacoes;
CREATE POLICY "Permitir leitura para auth" ON public.movimentacoes FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Permitir inserção para auth" ON public.movimentacoes;
CREATE POLICY "Permitir inserção para auth" ON public.movimentacoes FOR INSERT WITH CHECK (auth.role() = 'authenticated');


-- ========================================================
-- 4. Criação da tabela de Perfis de Usuário (Cargos/Hierarquia)
-- ========================================================
CREATE TABLE IF NOT EXISTS public.user_roles (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'user')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ativar RLS
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Permitir que os usuários leiam o próprio cargo
DROP POLICY IF EXISTS "Permitir leitura da propria role" ON public.user_roles;
CREATE POLICY "Permitir leitura da propria role" ON public.user_roles FOR SELECT USING (auth.uid() = user_id);

-- Função e Trigger para criar role de novo usuário automaticamente
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.user_roles (user_id, role)
  VALUES (new.id, 'user');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ========================================================
-- 5. Criação da tabela de Configuração da Balança
-- ========================================================
CREATE TABLE IF NOT EXISTS public.scale_configs (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    prefix_length INTEGER NOT NULL DEFAULT 1,
    plu_length INTEGER NOT NULL DEFAULT 4,
    value_length INTEGER NOT NULL DEFAULT 5,
    value_type TEXT NOT NULL DEFAULT 'price' CHECK (value_type IN ('price', 'weight')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ativar RLS
ALTER TABLE public.scale_configs ENABLE ROW LEVEL SECURITY;

-- Permitir leitura/escrita pelo próprio usuário
DROP POLICY IF EXISTS "Permitir leitura da propria config" ON public.scale_configs;
CREATE POLICY "Permitir leitura da propria config" ON public.scale_configs FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Permitir inserção/edição propria config" ON public.scale_configs;
CREATE POLICY "Permitir inserção/edição propria config" ON public.scale_configs FOR ALL USING (auth.uid() = user_id);
