-- Script de Criação e Configuração das Tabelas no Supabase
-- Cole este script no SQL Editor do Supabase e clique em 'Run'

-- 1. Criação da tabela de Produtos
CREATE TABLE IF NOT EXISTS public.produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PLU" TEXT NOT NULL,
    nome TEXT NOT NULL,
    preco NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    estoque INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Garante que não haverá produtos com o mesmo Código de Barras duplicado
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'produtos_plu_unique'
  ) THEN
    ALTER TABLE public.produtos ADD CONSTRAINT produtos_plu_unique UNIQUE ("PLU");
  END IF;
END $$;


-- 2. Criação da tabela de Vendas
CREATE TABLE IF NOT EXISTS public.vendas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    total NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    "totalItens" INTEGER NOT NULL DEFAULT 0,
    cliente TEXT,
    forma_pagamento TEXT NOT NULL,
    itens JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- 3. Criação da tabela de Movimentações (com Foreign Key)
CREATE TABLE IF NOT EXISTS public.movimentacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_movimentacao TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    produto_id BIGINT NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('ENTRADA', 'SAÍDA')),
    quantidade INTEGER NOT NULL CHECK (quantidade > 0),
    motivo TEXT,
    
    -- Foreign Key vinculando a movimentação ao produto
    -- ON DELETE CASCADE significa que se o produto for deletado, a movimentação some junto
    CONSTRAINT fk_produto
      FOREIGN KEY(produto_id) 
      REFERENCES public.produtos(id)
      ON DELETE CASCADE
);


-- ========================================================
-- Políticas de Segurança (RLS - Row Level Security)
-- ========================================================

-- Ativar RLS nas tabelas para que os dados sejam protegidos
ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movimentacoes ENABLE ROW LEVEL SECURITY;

-- Exemplo: Criar políticas permitindo acesso apenas a usuários autenticados
-- Obs: Se a sua aplicação compartilha os dados num geral e quem tem login tem acesso irrestrito.

-- PRODUTOS
DROP POLICY IF EXISTS "Permitir leitura para auth" ON public.produtos;
CREATE POLICY "Permitir leitura para auth" ON public.produtos FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Permitir inserção/edição para auth" ON public.produtos;
CREATE POLICY "Permitir inserção/edição para auth" ON public.produtos FOR ALL USING (auth.role() = 'authenticated');

-- VENDAS
DROP POLICY IF EXISTS "Permitir leitura para auth" ON public.vendas;
CREATE POLICY "Permitir leitura para auth" ON public.vendas FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Permitir inserção para auth" ON public.vendas;
CREATE POLICY "Permitir inserção para auth" ON public.vendas FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- MOVIMENTACOES
DROP POLICY IF EXISTS "Permitir leitura para auth" ON public.movimentacoes;
CREATE POLICY "Permitir leitura para auth" ON public.movimentacoes FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Permitir inserção para auth" ON public.movimentacoes;
CREATE POLICY "Permitir inserção para auth" ON public.movimentacoes FOR INSERT WITH CHECK (auth.role() = 'authenticated');
