-- Script de Criação e Configuração das Tabelas no Supabase
-- Cole este script no SQL Editor do Supabase e clique em 'Run'

-- 1. Criação da tabela de Produtos
CREATE TABLE IF NOT EXISTS public.produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PLU" TEXT NOT NULL,
    nome TEXT NOT NULL,
    preco NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    estoque NUMERIC(10, 3) NOT NULL DEFAULT 0,
    pesavel BOOLEAN NOT NULL DEFAULT false,
    controlar_estoque BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Adiciona as colunas na tabela existente caso necessário
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='produtos' AND column_name='pesavel') THEN
    ALTER TABLE public.produtos ADD COLUMN pesavel BOOLEAN NOT NULL DEFAULT false;
    ALTER TABLE public.produtos ALTER COLUMN estoque TYPE NUMERIC(10,3);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='produtos' AND column_name='controlar_estoque') THEN
    ALTER TABLE public.produtos ADD COLUMN controlar_estoque BOOLEAN NOT NULL DEFAULT true;
  END IF;
END $$;

-- Garante que não haverá duplicidade de PLU
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'produtos_plu_unique') THEN
    ALTER TABLE public.produtos ADD CONSTRAINT produtos_plu_unique UNIQUE ("PLU");
  END IF;
END $$;


-- 2. Criação da tabela de Vendas (Globais)
CREATE TABLE IF NOT EXISTS public.vendas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    total NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    "totalItens" INTEGER NOT NULL DEFAULT 0,
    cliente TEXT,
    forma_pagamento TEXT NOT NULL,
    itens JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'CONCLUIDA' CHECK (status IN ('CONCLUIDA', 'ENCOMENDA')),
    data_conclusao TIMESTAMP WITH TIME ZONE,
    valor_pago NUMERIC(10, 2),
    troco NUMERIC(10, 2),
    user_id UUID, -- Registra quem fez, mas o acesso é global
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- 3. Criação da tabela de Movimentações (Globais)
CREATE TABLE IF NOT EXISTS public.movimentacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_movimentacao TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    produto_id BIGINT NOT NULL REFERENCES public.produtos(id) ON DELETE CASCADE,
    tipo TEXT NOT NULL CHECK (tipo IN ('ENTRADA', 'SAÍDA')),
    quantidade NUMERIC(10, 3) NOT NULL CHECK (quantidade > 0),
    motivo TEXT
);


-- 4. TABELA DE CONFIGURAÇÃO GLOBAL DA LOJA (Recibo e Nome)
CREATE TABLE IF NOT EXISTS public.store_configs (
    id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1), -- Apenas um registro global (ID fixo)
    nome_loja TEXT NOT NULL DEFAULT 'Mercearia',
    endereco TEXT,
    rodape_recibo TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Inserir configuração padrão caso não exista
INSERT INTO public.store_configs (id, nome_loja, endereco, rodape_recibo)
VALUES (1, 'Mercearia', '', 'Obrigado pela preferência!')
ON CONFLICT (id) DO NOTHING;


-- 5. Configuração da Balança (Global) - DROP para resetar do modelo individual
DROP TABLE IF EXISTS public.scale_configs;
CREATE TABLE public.scale_configs (
    id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    prefix_length INTEGER NOT NULL DEFAULT 1,
    plu_length INTEGER NOT NULL DEFAULT 4,
    value_length INTEGER NOT NULL DEFAULT 5,
    value_type TEXT NOT NULL DEFAULT 'price' CHECK (value_type IN ('price', 'weight')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Inserir configuração de balança padrão
INSERT INTO public.scale_configs (id, prefix_length, plu_length, value_length, value_type)
VALUES (1, 1, 4, 5, 'price')
ON CONFLICT (id) DO NOTHING;


-- ========================================================
-- Políticas de Segurança (RLS Global para Auth)
-- ========================================================

ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movimentacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scale_configs ENABLE ROW LEVEL SECURITY;

-- Remover políticas restritivas anteriores
DROP POLICY IF EXISTS "Permitir leitura para auth" ON public.vendas;
DROP POLICY IF EXISTS "Permitir inserção para auth" ON public.vendas;
DROP POLICY IF EXISTS "Permitir atualização para auth" ON public.vendas;
DROP POLICY IF EXISTS "Permitir delete para auth" ON public.vendas;
DROP POLICY IF EXISTS "Permitir leitura para auth" ON public.produtos;
DROP POLICY IF EXISTS "Permitir inserção/edição para auth" ON public.produtos;
DROP POLICY IF EXISTS "Permitir leitura para auth" ON public.movimentacoes;
DROP POLICY IF EXISTS "Permitir leitura da propria config" ON public.scale_configs;
DROP POLICY IF EXISTS "Permitir inserção/edição propria config" ON public.scale_configs;

-- Criar novas políticas GLOBAIS (Acesso para qualquer usuário autenticado)

-- PRODUTOS
CREATE POLICY "Acesso Global Produtos" ON public.produtos FOR ALL USING (auth.role() = 'authenticated');

-- VENDAS
CREATE POLICY "Acesso Global Vendas" ON public.vendas FOR ALL USING (auth.role() = 'authenticated');

-- MOVIMENTACOES
CREATE POLICY "Acesso Global Movimentacoes" ON public.movimentacoes FOR ALL USING (auth.role() = 'authenticated');

-- CONFIG LOJA
CREATE POLICY "Acesso Global Store Config" ON public.store_configs FOR ALL USING (auth.role() = 'authenticated');

-- CONFIG BALANÇA
CREATE POLICY "Acesso Global Scale Config" ON public.scale_configs FOR ALL USING (auth.role() = 'authenticated');
